[perl]
disabled=true

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[✗](bold red)'


[hostname]
ssh_only = false
format = '@[$hostname](bold red)[$ssh_symbol](bold blue) '
trim_at = '.companyname.com'
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[time]
disabled = false
use_12hr = true

